<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>New Contact Enquiry - LegitBooks</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      margin: 0;
      padding: 24px;
      background-color: #f8fafc;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
      color: #111827;
    }
    .wrapper {
      max-width: 720px;
      margin: 0 auto;
    }
    .card {
      background-color: #ffffff;
      border-radius: 10px;
      border: 1px solid #e5e7eb;
      overflow: hidden;
      box-shadow: 0 6px 24px rgba(0,0,0,0.06);
    }
    .header {
      background-color: #392a26;
      padding: 20px 24px;
      color: #ffffff;
    }
    .header-title {
      margin: 0;
      font-size: 20px;
      font-weight: 600;
    }
    .header-subtitle {
      margin: 4px 0 0;
      font-size: 14px;
      opacity: 0.85;
    }
    .body {
      padding: 24px;
    }
    .meta {
      font-size: 12px;
      color: #6b7280;
      margin-bottom: 16px;
      text-align: right;
    }
    .section-title {
      font-size: 15px;
      font-weight: 600;
      margin: 0 0 10px;
      color: #1f2937;
    }
    .info-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 16px;
      font-size: 14px;
    }
    .info-table th {
      width: 130px;
      text-align: left;
      font-weight: 600;
      color: #374151;
      padding: 6px 0;
    }
    .info-table td {
      padding: 6px 0;
      color: #111827;
    }
    .divider {
      border-top: 1px solid #e5e7eb;
      margin: 18px 0;
    }
    .message-box {
      background-color: #f9fafb;
      border-radius: 8px;
      padding: 14px;
      border: 1px solid #e5e7eb;
      font-size: 14px;
      line-height: 1.5;
      color: #111827;
      white-space: pre-wrap;
    }
    .footer {
      background-color: #fafafa;
      padding: 16px 24px;
      font-size: 12px;
      color: #6b7280;
      border-top: 1px solid #f3f4f6;
    }
    .footer strong {
      color: #4b5563;
    }
    a.cta {
      display: inline-block;
      margin-top: 12px;
      padding: 10px 16px;
      background-color: #392a26;
      color: #ffffff !important;
      text-decoration: none;
      font-size: 14px;
      border-radius: 6px;
      font-weight: 600;
    }
  </style>
</head>
<body>

  <div class="wrapper">
    <div class="card">

      <div class="header">
        <h1 class="header-title">New Contact Enquiry</h1>
        <p class="header-subtitle">Submitted through the LegitBooks contact page</p>
      </div>

      <div class="body">

        <div class="meta">
          Received: {{ $submission->created_at ?? now() }}
        </div>

        <h2 class="section-title">Enquiry Details</h2>

        <table class="info-table" role="presentation">
          <tr>
            <th>Name</th>
            <td>{{ $submission->name ?? '—' }}</td>
          </tr>
          <tr>
            <th>Email</th>
            <td>{{ $submission->email ?? '—' }}</td>
          </tr>
          <tr>
            <th>Company</th>
            <td>{{ $submission->company ?? '—' }}</td>
          </tr>
          <tr>
            <th>Phone</th>
            <td>{{ $submission->phone ?? '—' }}</td>
          </tr>
        </table>

        <div class="divider"></div>

        <h2 class="section-title">Message</h2>
        <div class="message-box">
          {{ $submission->message ?? '—' }}
        </div>

        <a href="mailto:{{ $submission->email ?? '' }}" class="cta">
          Reply to Sender
        </a>

      </div>

      <div class="footer">
        <p style="margin: 0;">
          <strong>Internal Notice:</strong> This message was automatically generated by LegitBooks when a user submitted the contact form.
        </p>
      </div>

    </div>
  </div>

</body>
</html>

